# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.3.dev106+ga07f259.d20230126'
__version_tuple__ = version_tuple = (0, 3, 'dev106', 'ga07f259.d20230126')
